version: "3.9"

services:
  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  mysql-db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: file_db
      MYSQL_USER: chintan
      MYSQL_PASSWORD: Chintan@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
